echo =;
log archbishop.log;
mxram 1024;
proc archbishop.tnt;
taxcode -12 14 17 28 29 40 42 44;
taxcode +;
taxcode -;
taxname =;
hold 50000;

xmult=consense 3 noratchet verbose;
mult=tbr;

export = archbishop_ew.tre;
nelsen;
nelsen*; tchoose {strict}; export = archbishop_ew_strict.tre;

keep 0;
piwe=;
proc archbishop.tnt;
xpiwe=;

xmult;
mult=tbr;

export = archbishop_iw.tre;
nelsen;
nelsen*; tchoose {strict}; export = archbishop_iw_strict.tre;

log/;
