echo =;
log ecg.log;
mxram 2048;
proc archbishop.tnt;
taxcode -12 14 17 28 29 40 42 44;
taxcode +;
taxcode -;
taxname =;
hold 200000;

force = (Giraffatitan Archbishop);
force;
constrain =;

xmult=consense 2 noratchet verbose;
bbreak=tbr xbit safe;
export = ecg.tre;
export - ecg.export;

pcrprune;

nelsen*; tchoose {strict}; export = ecg-strict.tre;
tplot;

naked-;
tplot;

log ecg-apomorphies.log
tplot;
apo -;
apo;

log/;
quit;
