echo =;
log equalweights-constrained.log;
mxram 2048;
proc archbishop.tnt;
taxcode -12 14 17 28 29 40 42 44;
taxcode +;
taxcode -;
taxname =;
hold 200000;

force / (Shunosaurus (Saltasaurus (Brachiosaurus Archbishop)));;
constrain =;

xmult=consense 1 noratchet verbose;
bbreak=tbr xbit safe;
export = equalweights.tre;
export - equalweights.export;

pcrprune;

nelsen*; tchoose {strict}; export = equalweights-strict.tre;
tplot;

naked-;
tplot;

log equalweights-apomorphies.log
tplot;
apo -;
apo;

log/;
quit;
